### ISSUE TITLE
Les onglets de code du blog ne fonctionnent pas 

### ISSUE THREAD

**Issue by ameliedefrance** [Elao/elao_#272]
Lorsqu'on clique sur un onglet, la partie "code" disparaît. La classe `active` ne vient pas s'ajouter sur le bloc qui correspond à l'onglet sélectionné.

J'ai refait le css des onglets et j'ai modifié les classes originales ici : https://github.com/Elao/elao_/pull/269

NB : les onglets étaient déjà :broken-courgette: avant que je change les classes css

**Comment by Tom32i** [comment]
Réglé par la dernière mouture de stenope non ? @ogizanagi t'avais fait un fix sur les lien internes.

https://www.elao.com/blog/dev/ameliorez-pertinence-resultat-elastic-search-score

**Comment by ogizanagi** [comment]
Yes. On pourra tjrs voir à proposer une solution globale si ce besoin revient plus tard.
