### ISSUE TITLE
[Blog] - Image manquante ou mauvais path

### ISSUE THREAD

**Issue by gfaivre** [Elao/elao_#394]
Reçu par courriel: 

_Il manque une image dans l'article que tu as écris : https://www.elao.com/blog/infra/utiliser-supervisor-pour-controler-ses-services-applicatifs
Voilà la ligne concernée : ![Supervisor - Interface web supervisor](images/posts/2014/supervisor_web.png)
Merci pour ton travail,
Cdt_

**Comment by ogizanagi** [comment]
Hmm, le chemin est bon, l'image est là, mais elle n'est pas parsée correctement par Parsedown apparemment:

<img width="1057" alt="screenshot 2021-08-17 à 07 49 05" src="https://user-images.githubusercontent.com/2211145/129670573-af52b4ad-4a60-46a0-9bee-1501369ccb0b.png">
